config/routes.rb
Rails.application.routes.draw do
  resources :violations
  resources :stops
  resources :officers
  resources :locations
  resources :located_ats
  resources :gives
  resources :drivers
  get 'welcome/index'

  root 'welcome#index'

  get "/pages/:page" => "pages#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/officer.rb
class Officer < ApplicationRecord
  def self.q1
    find_by_sql("select gender1, warning, citation
                from
                (select officer_gender as gender1, count(*) * 100.0 / sum(count(*)) over() as warning
                from officers
                join gives on
                officers.officer_id = gives.officer_id
                join violations on
                gives.violation_id = violations.violation_id
                where stop_outcome = 'Warning'
                AND officer_gender is not null
                group by officer_gender)
                join
                (select officer_gender gender2, count(*) * 100.0 / sum(count(*)) over() as citation
                from officers
                join gives on
                officers.officer_id = gives.officer_id
                join violations on
                gives.violation_id = violations.violation_id
                where stop_outcome = 'Citation'
                AND officer_gender is not null
                group by officer_gender)
                on gender1 = gender2")
  end

  def self.q2
    find_by_sql("SELECT
        officers.officer_race as race,
        STATS_MODE(violations.violation_type) AS v_type
    FROM
        located_at
        INNER JOIN violations ON located_at.violation_id = violations.violation_id
        INNER JOIN officers ON located_at.officer_id = officers.officer_id
    WHERE officer_race IS NOT NULL
    GROUP BY
        officers.officer_race")
    end
end

app/controllers/officers_controller.rb
class OfficersController < ApplicationController
  before_action :set_officer, only: [:show, :edit, :update, :destroy]

  # GET /officers
  # GET /officers.json
  def index
    @officers1 = Officer.q1

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @officers1 }
    end

    @officers2 = Officer.q2

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @officers2 }
    end
  end

  # GET /officers/1
  # GET /officers/1.json
  def show
  end

  # GET /officers/new
  def new
    @officer = Officer.new
  end

  # GET /officers/1/edit
  def edit
  end

  # POST /officers
  # POST /officers.json
  def create
    @officer = Officer.new(officer_params)

    respond_to do |format|
      if @officer.save
        format.html { redirect_to @officer, notice: 'Officer was successfully created.' }
        format.json { render :show, status: :created, location: @officer }
      else
        format.html { render :new }
        format.json { render json: @officer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /officers/1
  # PATCH/PUT /officers/1.json
  def update
    respond_to do |format|
      if @officer.update(officer_params)
        format.html { redirect_to @officer, notice: 'Officer was successfully updated.' }
        format.json { render :show, status: :ok, location: @officer }
      else
        format.html { render :edit }
        format.json { render json: @officer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /officers/1
  # DELETE /officers/1.json
  def destroy
    @officer.destroy
    respond_to do |format|
      format.html { redirect_to officers_url, notice: 'Officer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_officer
      @officer = Officer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def officer_params
      params.require(:officer).permit(:officer_gender, :officer_age, :officer_race, :officer_rank)
    end
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/views/officers/_form.html.erb
<%= form_with(model: officer, local: true) do |form| %>
  <% if officer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(officer.errors.count, "error") %> prohibited this officer from being saved:</h2>

      <ul>
      <% officer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :officer_gender %>
    <%= form.text_field :officer_gender, id: :officer_officer_gender %>
  </div>

  <div class="field">
    <%= form.label :officer_age %>
    <%= form.number_field :officer_age, id: :officer_officer_age %>
  </div>

  <div class="field">
    <%= form.label :officer_race %>
    <%= form.text_field :officer_race, id: :officer_officer_race %>
  </div>

  <div class="field">
    <%= form.label :officer_rank %>
    <%= form.text_field :officer_rank, id: :officer_officer_rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/officers/edit.html.erb
<h1>Editing Officer</h1>

<%= render 'form', officer: @officer %>

<%= link_to 'Show', @officer %> |
<%= link_to 'Back', officers_path %>

app/views/officers/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Officers</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'officers', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
</head>

<body>
  <h1>Officer Query Selection</h1>
  <div class="btn-list">
    <a id="qButton" href="javascript:showhide('r1')">
      Percentage of citations or warnings given based on officer's gender
    </a>
    <div class=“result” id="r1" style="display:none;">
      <h4>Warnings Given</h4>
      <%= pie_chart @officers1.pluck(:gender1,:warning) %>
      <h4>Citations Given</h4>
      <%= pie_chart @officers1.pluck(:gender1,:citation) %>
      <h4>Analysis: There is no difference in the stop outcome based on gender. Note that the number of female officers is significantly less than the number of male officers</h4>
    </div>

    <a id="qButton" href="javascript:showhide('r2')">
      Top violation issued by officer of each race
    </a>
    <div class=“result” id="r2" style="display:none;">
      <% @officers2.each do |officer| %>
        <tr>
          <p><%= officer.race %> : <%= officer.v_type %></p>
        </tr>  
      <% end %>
    </div>
  </div>
</body>

app/views/officers/new.html.erb
<h1>New Officer</h1>

<%= render 'form', officer: @officer %>

<%= link_to 'Back', officers_path %>

app/views/officers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Officer gender:</strong>
  <%= @officer.officer_gender %>
</p>

<p>
  <strong>Officer age:</strong>
  <%= @officer.officer_age %>
</p>

<p>
  <strong>Officer race:</strong>
  <%= @officer.officer_race %>
</p>

<p>
  <strong>Officer rank:</strong>
  <%= @officer.officer_rank %>
</p>

<%= link_to 'Edit', edit_officer_path(@officer) %> |
<%= link_to 'Back', officers_path %>