config/routes.rb
Rails.application.routes.draw do
  resources :violations
  resources :stops
  resources :officers
  resources :locations
  resources :located_ats
  resources :gives
  resources :drivers
  get 'welcome/index'

  root 'welcome#index'

  get "/pages/:page" => "pages#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/violation.rb
class Violation < ApplicationRecord
  def self.q1
    find_by_sql("select * from
                (select violation_type, count(*) as v_count
                from violations
                where violation_type like 'Lights'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Paperwork'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Registration/plates'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Safe movement'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Speeding'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Seat belt'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Equipment'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'DUI'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'Other'
                group by violation_type
                UNION
                select violation_type, count(*)
                from violations
                where violation_type like 'License'
                group by violation_type)
                order by v_count desc")
  end

  def self.q2
    find_by_sql("SELECT stop_date, COUNT(violation_id) as v_count
                FROM located_at
                GROUP BY stop_date")
    end            
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController
  before_action :set_violation, only: [:show, :edit, :update, :destroy]

  # GET /violations
  # GET /violations.json
  def index
    @violations1 = Violation.q1

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @violations1 }
    end

    @violations2 = Violation.q2

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @violations2 }
    end
  end

  # GET /violations/1
  # GET /violations/1.json
  def show
  end

  # GET /violations/new
  def new
    @violation = Violation.new
  end

  # GET /violations/1/edit
  def edit
  end

  # POST /violations
  # POST /violations.json
  def create
    @violation = Violation.new(violation_params)

    respond_to do |format|
      if @violation.save
        format.html { redirect_to @violation, notice: 'Violation was successfully created.' }
        format.json { render :show, status: :created, location: @violation }
      else
        format.html { render :new }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /violations/1
  # PATCH/PUT /violations/1.json
  def update
    respond_to do |format|
      if @violation.update(violation_params)
        format.html { redirect_to @violation, notice: 'Violation was successfully updated.' }
        format.json { render :show, status: :ok, location: @violation }
      else
        format.html { render :edit }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /violations/1
  # DELETE /violations/1.json
  def destroy
    @violation.destroy
    respond_to do |format|
      format.html { redirect_to violations_url, notice: 'Violation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_violation
      @violation = Violation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def violation_params
      params.require(:violation).permit(:violation_type, :stop_outcome, :is_arrested)
    end
end

app/helpers/violations_helper.rb
module ViolationsHelper
end

app/views/violations/_form.html.erb
<%= form_with(model: violation, local: true) do |form| %>
  <% if violation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(violation.errors.count, "error") %> prohibited this violation from being saved:</h2>

      <ul>
      <% violation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :violation_type %>
    <%= form.text_field :violation_type, id: :violation_violation_type %>
  </div>

  <div class="field">
    <%= form.label :stop_outcome %>
    <%= form.text_field :stop_outcome, id: :violation_stop_outcome %>
  </div>

  <div class="field">
    <%= form.label :is_arrested %>
    <%= form.text_field :is_arrested, id: :violation_is_arrested %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/violations/edit.html.erb
<h1>Editing Violation</h1>

<%= render 'form', violation: @violation %>

<%= link_to 'Show', @violation %> |
<%= link_to 'Back', violations_path %>

app/views/violations/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Violation</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'violations', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
</head>

<body>
  <h1>Violation Query Selection</h1>
  <div class="btn-list">
    <a id="qButton" href="javascript:showhide('r1')">
      Count of each violation type committed
    </a>
    <div class=“result” id="r1" style="display:none;">
      <%= bar_chart @violations1.pluck(:violation_type,:v_count) %>
    </div>

    <a id="qButton" href="javascript:showhide('r2')">
      How many violations occurred in any given day
    </a>
    <div class=“result” id="r2" style="display:none;">
      <%= line_chart @violations2.pluck(:stop_date,:v_count) %>
    </div>
  </div>
</body>

app/views/violations/new.html.erb
<h1>New Violation</h1>

<%= render 'form', violation: @violation %>

<%= link_to 'Back', violations_path %>

app/views/violations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Violation type:</strong>
  <%= @violation.violation_type %>
</p>

<p>
  <strong>Stop outcome:</strong>
  <%= @violation.stop_outcome %>
</p>

<p>
  <strong>Is arrested:</strong>
  <%= @violation.is_arrested %>
</p>

<%= link_to 'Edit', edit_violation_path(@violation) %> |
<%= link_to 'Back', violations_path %>