config/routes.rb
Rails.application.routes.draw do
  resources :violations
  resources :stops
  resources :officers
  resources :locations
  resources :located_ats
  resources :gives
  resources :drivers
  get 'welcome/index'

  root 'welcome#index'

  get "/pages/:page" => "pages#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/located_at.rb
class LocatedAt < ApplicationRecord
  belongs_to :officer
  belongs_to :violation
end

app/controllers/located_ats_controller.rb
class LocatedAtsController < ApplicationController
  before_action :set_located_at, only: [:show, :edit, :update, :destroy]

  # GET /located_ats
  # GET /located_ats.json
  def index
    @located_ats = LocatedAt.all
  end

  # GET /located_ats/1
  # GET /located_ats/1.json
  def show
  end

  # GET /located_ats/new
  def new
    @located_at = LocatedAt.new
  end

  # GET /located_ats/1/edit
  def edit
  end

  # POST /located_ats
  # POST /located_ats.json
  def create
    @located_at = LocatedAt.new(located_at_params)

    respond_to do |format|
      if @located_at.save
        format.html { redirect_to @located_at, notice: 'Located at was successfully created.' }
        format.json { render :show, status: :created, location: @located_at }
      else
        format.html { render :new }
        format.json { render json: @located_at.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /located_ats/1
  # PATCH/PUT /located_ats/1.json
  def update
    respond_to do |format|
      if @located_at.update(located_at_params)
        format.html { redirect_to @located_at, notice: 'Located at was successfully updated.' }
        format.json { render :show, status: :ok, location: @located_at }
      else
        format.html { render :edit }
        format.json { render json: @located_at.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /located_ats/1
  # DELETE /located_ats/1.json
  def destroy
    @located_at.destroy
    respond_to do |format|
      format.html { redirect_to located_ats_url, notice: 'Located at was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_located_at
      @located_at = LocatedAt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def located_at_params
      params.require(:located_at).permit(:stop_date, :stop_time, :county_fips, :driver_gender, :driver_race, :driver_age, :officer_id, :violation_id)
    end
end

app/helpers/located_ats_helper.rb
module LocatedAtsHelper
end

app/views/located_ats/_form.html.erb
<%= form_with(model: located_at, local: true) do |form| %>
  <% if located_at.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(located_at.errors.count, "error") %> prohibited this located_at from being saved:</h2>

      <ul>
      <% located_at.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stop_date %>
    <%= form.text_field :stop_date, id: :located_at_stop_date %>
  </div>

  <div class="field">
    <%= form.label :stop_time %>
    <%= form.text_field :stop_time, id: :located_at_stop_time %>
  </div>

  <div class="field">
    <%= form.label :county_fips %>
    <%= form.number_field :county_fips, id: :located_at_county_fips %>
  </div>

  <div class="field">
    <%= form.label :driver_gender %>
    <%= form.text_field :driver_gender, id: :located_at_driver_gender %>
  </div>

  <div class="field">
    <%= form.label :driver_race %>
    <%= form.text_field :driver_race, id: :located_at_driver_race %>
  </div>

  <div class="field">
    <%= form.label :driver_age %>
    <%= form.number_field :driver_age, id: :located_at_driver_age %>
  </div>

  <div class="field">
    <%= form.label :officer_id %>
    <%= form.text_field :officer_id, id: :located_at_officer_id %>
  </div>

  <div class="field">
    <%= form.label :violation_id %>
    <%= form.text_field :violation_id, id: :located_at_violation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/located_ats/edit.html.erb
<h1>Editing Located At</h1>

<%= render 'form', located_at: @located_at %>

<%= link_to 'Show', @located_at %> |
<%= link_to 'Back', located_ats_path %>

app/views/located_ats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Located Ats</h1>

<table>
  <thead>
    <tr>
      <th>Stop date</th>
      <th>Stop time</th>
      <th>County fips</th>
      <th>Driver gender</th>
      <th>Driver race</th>
      <th>Driver age</th>
      <th>Officer</th>
      <th>Violation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @located_ats.each do |located_at| %>
      <tr>
        <td><%= located_at.stop_date %></td>
        <td><%= located_at.stop_time %></td>
        <td><%= located_at.county_fips %></td>
        <td><%= located_at.driver_gender %></td>
        <td><%= located_at.driver_race %></td>
        <td><%= located_at.driver_age %></td>
        <td><%= located_at.officer %></td>
        <td><%= located_at.violation %></td>
        <td><%= link_to 'Show', located_at %></td>
        <td><%= link_to 'Edit', edit_located_at_path(located_at) %></td>
        <td><%= link_to 'Destroy', located_at, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Located At', new_located_at_path %>

app/views/located_ats/new.html.erb
<h1>New Located At</h1>

<%= render 'form', located_at: @located_at %>

<%= link_to 'Back', located_ats_path %>

app/views/located_ats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stop date:</strong>
  <%= @located_at.stop_date %>
</p>

<p>
  <strong>Stop time:</strong>
  <%= @located_at.stop_time %>
</p>

<p>
  <strong>County fips:</strong>
  <%= @located_at.county_fips %>
</p>

<p>
  <strong>Driver gender:</strong>
  <%= @located_at.driver_gender %>
</p>

<p>
  <strong>Driver race:</strong>
  <%= @located_at.driver_race %>
</p>

<p>
  <strong>Driver age:</strong>
  <%= @located_at.driver_age %>
</p>

<p>
  <strong>Officer:</strong>
  <%= @located_at.officer %>
</p>

<p>
  <strong>Violation:</strong>
  <%= @located_at.violation %>
</p>

<%= link_to 'Edit', edit_located_at_path(@located_at) %> |
<%= link_to 'Back', located_ats_path %>